version: '3.1'

services:
  postgresql:
    image: postgres
    container_name: pg_container
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - mydata:/home/db/data/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: consultants

volumes:
  mydata: {}
